baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false

  readMore = "Read more"
  keywords = ""
  writtenBy = "Written by"
  dateFormatSingle = "2006-01-02"
  dateFormatList = "2006-01-02"
  subtitle = "A simple theme for Hugo"
  title = "Hello Friend"
  copyright = ""
  menuMore = "Show more"
  readOtherPosts = "Read other posts"
  newerPosts = "Newer posts"
  olderPosts = "Older posts"
  minuteReadingTime = "min read"

[languages]
  [languages.en]

    [languages.en.params.logo]
      logoText = "hello friend"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
